# Application Configuration
base.url=https://demoqa.com
login.page.url=https://demoqa.com/books

# Browser Configuration
browser=chrome
headless=false

# Timeout Configuration
implicit.wait=10
explicit.wait=15
